"""auto votes

Revision ID: 8642517fb5bd
Revises: 799bd818df84
Create Date: 2022-01-05 15:56:42.708356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642517fb5bd'
down_revision = '799bd818df84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
